name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docs:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Dokka
      run: ./gradlew :parse:dokkaHtml
    - name: GitHub Pages action
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_dir: "./parse/build/dokka/html"
